export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT= 'AUTH_LOGOUT'

export const authConstants = {
  LOGIN_REQUEST:'LOGIN_REQUEST',
  LOGIN_FAILURE:'LOGIN_FAILURE',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  LOGOUT:'LOGOUT',

  SIGNUP_REQUEST:'SIGNUP_REQUEST',
  SIGNUP_FAILURE:'SIGNUP_FAILURE',
  SIGNUP_SUCCESS:'SIGNUP_SUCCESS'
}