

export const authConstants = {
  LOGIN_REQUEST:'LOGIN_REQUEST',
  LOGIN_FAILURE:'LOGIN_FAILURE',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  LOGOUT:'LOGOUT',

  SIGNUP_REQUEST:'SIGNUP_REQUEST',
  SIGNUP_FAILURE:'SIGNUP_FAILURE',
  SIGNUP_SUCCESS:'SIGNUP_SUCCESS',

  REFRESH_REQUEST : 'REFRESH_REQUEST',
  REFRESH_FAILURE : 'REFRESH_FAILURE',
  REFRESH_SUCCESS : 'REFRESH_SUCCESS'
}